### ISSUE TITLE
Unclear license statements

### ISSUE THREAD

**Issue by stefan6419846** [ZUGFeRD/corpus#8]
Having a look at https://github.com/ZUGFeRD/corpus/tree/master/XML-Rechnung, I am trying to determine which license statements hold true for the individual files.

What I have seen so far:

* There is a license file with the Apache-2.0 license text.
* In the CII files, there is a custom copyright header.
* In the UBL files, there is no copyright. According to the README, they have been generated automatically from the CII files(?)
* In the FX files, the embedded XML data has the custom copyright header known from the CII files.

The custom copyright headers contain the following sentences:

> FeRD grants a license for the use of the copyrighted ZUGFeRD data format in the respective 
> valid and accepted version (www.ferd-net.de). 
> The license includes an irrevocable right of use including the right of further development, 
> Further processing and connection with other products.

For me, these sentences contradict each other: If the license grant cannot be revoked, why does the first sentence refer to the currently valid version only (in German: "in der jeweils geltenden und akzeptierten Fassung")? From my understanding, the first sentence would mean that I cannot use/ship files of old ZUGFeRD data format versions, despite the rights being granted irrevocably.

Could you please clarify the license terms? Are all files subject to the Apache-2.0 license and the headers are only meant to provide a shorter summary of the terms?

**Comment by jstaerk** [comment]
Hi, can you PR a removal?

**Comment by stefan6419846** [comment]
What removal do you expect in a PR? In the meantime, I stumbled upon the fact that these headers and sample files seem to originate from the official FeRD downloads, thus just changing them does not feel right.

**Comment by jstaerk** [comment]
if the license is invalid you can PR the removal of the files in question

**Comment by jstaerk** [comment]
I've asked the lawyer who invented ZUGFeRD, he considers the statement APL compatible and mentioned it was actually designed to be compatible precisely to the apache public license
